# Source: http://www.ameyalokare.com/docker/2017/09/20/nginx-flask-postgres-docker-compose.html
 
version: '3'
services:
  db:
    image: "postgres:9.6.5"
    env_file:
      - database.py
    networks:
      - db_nw
  flaskapp:
    build: .
    volumes:
      - .:/opt/services/flaskapp/src
    networks:
      - db_nw
      - web_nw
  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
networks: 
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge